# Generated by Django 4.1.13 on 2024-03-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.CharField(default='hello', max_length=500),
            preserve_default=False,
        ),
    ]
